### PR TITLE
Test for cmd line "obj" command after change of argument syntax

### PR DESCRIPTION
**Pull request by pwalczysko**
Replace by https://github.com/mtbc/openmicroscopy/pull/14

See https://github.com/openmicroscopy/openmicroscopy/pull/4672#issuecomment-220339279 and https://github.com/openmicroscopy/openmicroscopy/pull/4672#issuecomment-221810038. These are the discussed tests for making sure the arguments such as `arg1, arg2`  of following example `bin/omero obj ....arg1=x arg2=y...`  can:
- be a character followed by number (done here for 2 cases, AffineTransform and Line roi
- be a character (already covered in existing tests, e.g. [name of dataset](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/test/integration/clitest/test_obj.py#L67), not dealt with in this PR
- cannot be a number followed by letters, done in https://github.com/mtbc/openmicroscopy/commit/d95094e5af23a506d293c0b0d0a7018e5b64b91f in `test_fail_leading_numbers_argument`
- cannot be a number, also done in https://github.com/mtbc/openmicroscopy/commit/d95094e5af23a506d293c0b0d0a7018e5b64b91f here in `test_fail_leading_numbers_argument`

I did not do any iterations and post-checks except:
- checking that the Line was updated as intended using the `obj get...` command and comparing the `y2` value, verifying that the arguments of the preceding `obj update....` were passed successfully
- checking that the AffineTransform `obj new...` output contains just `AffineTransorm:ID`, i.e. the action did not fail and thus the arguments were passed succesfully

### CODE REVIEW

**Comment by pwalczysko** [comment]
@mtbc : the first commit is something which I had locally as I was told that without this PR of Dom I will not get the transforms running... Not sure what to do at this stage to get rid of it ?

**Comment by mtbc** [comment]
Yeah, you have an interesting git issue there. :smiley: I can help you fix it on Monday if nobody else does so first. Easiest might be to branch from my PR's branch then cherry-pick your commits over to it. @sbesson, @ximenesuk, do the tests look good to you? At first look they seem to me to fit well.

**Comment by pwalczysko** [comment]
I opted for reverting the commit, but to my surprise this did not really revert it, but added a "revert" commit instead. Maybe not optimal...

**Comment by pwalczysko** [comment]
This looks to me like irreparably damaged now. Closing. Sorry for any confusion. Replacing by https://github.com/mtbc/openmicroscopy/pull/14

**Pull request closed without merging**
