### PR TITLE
Use Requests util in Matlab example

### PR DESCRIPTION
**Pull request by dominikl**
Use `omero.gateway.util.Requests` instead of the `Delete2` command directly.

### CODE REVIEW

**Comment by mtbc** [comment]
Couple of questions:

* Was part of the point of the example's separate deletions to show the deletion of only a ROI?

* Won't the ROI be deleted automatically when the Image is? (Unless the ROI's in a Folder.) Might need to make it clearer that in many cases automatically ROIs go with their images.

I'm fine with the answer to the first being "no, no point" and the second being "but nice to have an example of using `includeType`"! Neither are blockers, just trying to think it through before merging into what I suspect is already a mergeable PR. Cc: @sbesson.

**Comment by dominikl** [comment]
I thought deleting the ROI and then deleting the Image is actually unnecessary, would work both the same way. I wasn't actually sure, if the ROI will be deleted without the include option. But yes, would be good to show that as an example. And if it is deleted also without the option, maybe just mention that as comment.
Ah, if the PR is already mergeable, then I can just open a separate one with this commit. If not to late, PR freeze etc.

**Comment by jburel** [comment]
@dominikl this is more a bug fix since the code will then be used for the doc

**Comment by sbesson** [comment]
Answering https://github.com/mtbc/openmicroscopy/pull/15#issuecomment-327505085 and re-reading https://github.com/openmicroscopy/openmicroscopy/pull/3552#issuecomment-76925123, I think the ROI deletion step was both for initially introduced for testing convenience and grouping purposes.

Generally, using the training example to cover multiple requests scenario (ROI only, Image with ROIs, `includeType`) makes complete sense. In this case, slight preference for keeping the current semantics (delete the ROI first then the image) in case people are watching this example for changes.

**Comment by dominikl** [comment]
I'll create a separate PR for this.

**Pull request closed without merging**
